version: "2"
linters:
  enable:
    - misspell
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/tokuhirom/dcv
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
