version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dcv
    main: ./main.go
    binary: dcv
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

archives:
  - id: dcv
    name_template: >-
      {{- .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    builds:
      - dcv

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: tokuhirom
    name: dcv
  draft: false
  prerelease: auto
  mode: replace
  name_template: "{{.ProjectName}} v{{.Version}}"

brews:
  - repository:
      owner: tokuhirom
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    name: dcv
    homepage: "https://github.com/tokuhirom/dcv"
    description: "Docker Compose Viewer - A TUI tool for monitoring Docker Compose applications"
    license: "MIT"
    test: |
      system "#{bin}/dcv", "--version"
    install: |
      bin.install "dcv"

winget:
  - name: tokuhirom.dcv
    publisher: tokuhirom
    short_description: "Docker Compose Viewer - A TUI tool for monitoring Docker containers"
    description: |
      DCV (Docker Container Viewer) is a TUI tool for monitoring Docker containers and Docker Compose applications.
      It provides an interactive interface to manage containers, images, networks, and volumes with vim-like navigation.
    license: MIT
    publisher_url: https://github.com/tokuhirom
    publisher_support_url: https://github.com/tokuhirom/dcv/issues
    homepage: https://github.com/tokuhirom/dcv
    license_url: https://github.com/tokuhirom/dcv/blob/main/LICENSE
    copyright: Copyright (c) 2025 Tokuhiro Matsuno
    tags:
      - docker
      - docker-compose
      - tui
      - container
      - monitoring
      - devops
      - cli
    repository:
      owner: microsoft
      name: winget-pkgs
      branch: master
      token: "{{ .Env.WINGET_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        draft: false
        base:
          owner: microsoft
          name: winget-pkgs
          branch: master