services:
  # Web application
  web:
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - dcv-network

  # Database
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: dcvuser
      POSTGRES_PASSWORD: dcvpass
      POSTGRES_DB: dcvdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dcv-network

  # Redis cache
  redis:
    image: redis:8-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - dcv-network

  # Docker in Docker for CI/CD simulation
  dind:
    image: docker:28-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - dind-storage:/var/lib/docker
      - ./dind-startup.sh:/startup.sh:ro
      - ./dind-entrypoint.sh:/entrypoint.sh:ro
    networks:
      - dcv-network
    entrypoint: ["/entrypoint.sh"]
    command: ["dockerd", "--host=unix:///var/run/docker.sock", "--host=tcp://0.0.0.0:2375"]

  # Verbose logger container that outputs messages periodically
  logger:
    image: alpine:latest
    command: |
      sh -c "
        counter=1
        while true; do
          echo \"[$(date '+%Y-%m-%d %H:%M:%S')] Logger message #$$counter: Hello from verbose container!\"
          echo \"[$(date '+%Y-%m-%d %H:%M:%S')] System info: $(uname -a)\"
          echo \"[$(date '+%Y-%m-%d %H:%M:%S')] Memory usage: $(free -h | grep Mem | awk '{print $$3 \"/\" $$2}')\"
          echo \"[$(date '+%Y-%m-%d %H:%M:%S')] Random data: $(head -c 32 /dev/urandom | base64)\"
          echo \"----------------------------------------\"
          counter=$$((counter + 1))
          sleep 2
        done
      "
    networks:
      - dcv-network

volumes:
  postgres-data:
  redis-data:
  dind-storage:

networks:
  dcv-network:
    driver: bridge