name: Generate Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'internal/ui/keymap.go'
      - 'internal/ui/command_*.go'
      - 'cmd/generate-docs/main.go'
      - '.github/workflows/generate-docs.yml'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    
    - name: Generate keymap documentation
      run: |
        go run cmd/generate-docs/main.go docs/keymap.md
    
    - name: Check for changes
      id: verify-changed-files
      run: |
        git diff --exit-code docs/keymap.md || echo "changed=true" >> $GITHUB_OUTPUT
    
    - name: Commit and push if changed
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/keymap.md
        git commit -m "chore: auto-generate keymap documentation

        🤖 Generated with GitHub Actions

        Co-Authored-By: GitHub Actions <action@github.com>"
        git push